export interface Paper {
  id: string;
  title: string;
  authors: string;
}

export const papers2024: Paper[] = [
  { id: '001', title: 'INSIGHTS INTO SUSTAINABILITY INTEGRATION AND TOP PRIORITIES FOR GREEN AND DIGITAL TRANSITION IN LOGISTICS', authors: 'Maja Rosi, Matevž Obracht' },
  { id: '002', title: 'THE INTEGRATED QUALITY MANAGEMENT SYSTEM IN FUNCTION OF ENVIRONMENTAL PROTECTION: MONTENEGRO AS A CASE STUDY', authors: 'Aleksandar Vujović, Jelena Šaković Jovanović, Marija Bogdanović Vujović' },
  { id: '003', title: 'CAN ESG PRINCIPLES CONFLICT WITH CENTRAL BANK POLICIES?', authors: 'Fabris Nikola, Radoica Luburić' },
  { id: '004', title: 'THE ROLE OF DATABASES IN EFFECTIVE NONCONFORMITY MANAGEMENT IN INDUSTRY 4.0 ', authors: 'Milan Erić, Miladin Stefanović, Slobodan Mitrović, Dragan Džunić, Aleksandar Đorđević' },
  { id: '005', title: 'THE INTEGRATION OF LEAN, GREEN AND SUSTAINABLE BUSINESS PRACTICES: FROM LITERATURE REVIEW TO THE DEVELOPMENT MODEL', authors: 'Zorana Stanković, Milena Rajić, Peđa Milosavljević and Dragan Pavlović' },
  { id: '006', title: 'SMART SOLUTIONS FOR SMART CITIES - VETSOL (Application of renewable resources in urban areas) ', authors: 'Zoran Anišić and Emil Peić Tukuljac' },
  { id: '007', title: 'APPLICATION OF SOLAR ENERGY IN WATER TREATMENT', authors: 'Tijana Đuričić, Draženko Bjelić, Aleksandra Borković, Dajana Dragić, Sanda Pilipović and Borislav N. Malinović' },
  { id: '008', title: 'STRATEGIES FOR MINIMIZING SICKNESS ABSENTEEISM IN INDUSTRY 5.0 MANUFACTURING SETTINGS  ', authors: 'Aleksandra Sitarević and Ognjen Dopuđ' },
  { id: '009', title: 'COMPREHENSIVE APPROACHES TO LITHIUM BATTERY RECYCLING IN THE ERA OF CIRCULAR ECONOMY', authors: 'Jelena Mitrović and Aleksandra Stevanović' },
  { id: '010', title: 'EXAMINING THE RELATIONSHIP BETWEEN CHATGPT, GEMINI, AND BING USE AND LIFE SATISFACTION: A CASE STUDY OF SLOVENIA ', authors: 'Anton Vorina, Tina Vorina, Vid Vorina and Svit Vorina' },
  { id: '011', title: 'FROM RISK TO SUSTAINABILITY: IMPROVING LITHIUM-ION BATTERY SAFETY FOR SUSTAINABLE ENERGY APPLICATIONS', authors: 'Aleksandra Stevanović and Jelena Mitrović' },
  { id: '012', title: 'FROM FRAGILE TO AGILE: BOLSTERING ORGANISATIONAL RESILIENCE THROUGH AGILE TRANSFORMATION ', authors: 'Bojan Grebic, Danijela Ciric Lalic, Milena Savkovic, Danijela Gracanin and Dragan Dakić' },
  { id: '013', title: 'CURRENT TRENDS IN UPSKILLING AND RESKILLING: ANALYZING MODERN LEARNING AND DEVELOPMENT PROGRAMS', authors: 'Katarina Milošević and Ivana Katić' },
  { id: '014', title: 'DIGITAL TRANSFORMATION AND HR TECHNOLOGY – INTEGRATING AI INTO TALENT ACQUISITION AND RETENTION OF EMPLOYEES ', authors: 'Katarina Milošević and Ivana Katić' },
  { id: '015', title: 'INTEGRATING SUSTAINABILITY AND CIRCULAR ECONOMY PRINCIPLES IN LEADERSHIP AMIDST UNCERTAINTY', authors: 'Mirjana Ratić, Jelena Ćulibrk, Nemanja Tasić, Maja Petrović and Nenad Medić' },
  { id: '016', title: 'DIGITAL TECHNOLOGIES AS SUSTAINABILITY ENABLERS ', authors: 'Dragana Slavić, Nenad Medić, Branko Markoski and Slavko Rakić' },
  { id: '017', title: 'STATE TERRORISM – POLITICAL-SECURITY AND CRIMINAL ASPECT', authors: 'Borisa Lecic' },
  { id: '018', title: 'ENVIRONMENTAL MANAGEMENT SYSTEMS CERTIFICATION IN SERBIA: THE INFLUENCE OF TRADE AND ENVIRONMENT ', authors: 'Aleksandra Pavlović, Andrea Ivanišević, Aleksandra Nastasić, Aleksandar Takači, Ranko Makivić and Katarina Stojanović' },
  { id: '019', title: 'HEALTHCARE SERVICE QUALITY ON PATIENT LOYALTY IN ZAMBIA', authors: 'Vimal Somaiya and Masatoshi Hara' },
  { id: '020', title: 'THE BALANCING ACT OF MANAGING FINANCIAL LIMITATIONS WHILE ACHIEVING MISSION SUCCESS: A STUDY OF NONPROFIT ORGANIZATIONS ', authors: 'Paulraj Joseph and Praveen Kumar' },
  { id: '021', title: 'EFFECTIVE MANAGEMENT OF CCS PROJECTS: ADVANCING WITH AN INTEGRATED CCS MODEL', authors: 'Serguei Fominykh and Danijela Gračanin' },
  { id: '022', title: 'ENTERPRISE DATA MANAGEMENT, DESIGN OF A CONCEPTUAL MODEL FOR EFFECTIVE DATA GOVERNANCE FRAMEWORK IN LARGE ORGANIZATIONS ', authors: 'ChadwickThompson Okoye' },
  { id: '023', title: 'IN THE FACE OF NEW GLOBAL BUSINESS CHALLENGES WITH STRONG RESPONSIBILITY OF THE INDIVIDUAL TOWARDS WORK', authors: 'Gala Šikoparija, Jelena Ćulibrk, Bojana Jokanović, Nenad Simeunović and Dunja Bošković' },
  { id: '024', title: 'THE AHP APPROACH IN SELECTING CANDIDATES FOR THE POSITION OF STRATEGIC PLANNING MANAGER ', authors: 'Dragana Gardašević, Milanka Gardašević Filipović and Koviljka Banjević' },
  { id: '025', title: 'AN OVERVIEW OF OVERTOURISM: CAUSES AND IMPACTS', authors: 'Snežana Milićević and Nataša Đorđević' },
  { id: '026', title: 'DISCUSSION ON SERBIA’S WASTE MANAGEMENT CHALLENGES AND FUTURE DIRECTIONS ', authors: 'Maja Jokic and Anna Frank' },
  { id: '027', title: 'THE APPLICATION OF ESG INSTRUMENTS AS A FUTURE CHALLENGE FOR SUSTAINABLE DEVELOPMENT IN CORPORATE GOVERNANCE', authors: 'Marijana Dukić Mijatović, Andrea Ivanišević, Danijela Gracanin and Danijela Ćirić Lalić' },
  { id: '028', title: '(SELF-) MANAGEMENT OF THE ICT-SUPPORTED DIGITAL NOMADISM IN CREATIVE INDUSTRIES ', authors: 'Žikica Milošević and Aleksandar Babić' },
  { id: '029', title: 'CHALLENGES IN TEACHING MATHEMATICS AND STATISTICS IN MODERN TIMES', authors: 'Aleksandar Takaci and Gordana Stankov' },
  { id: '030', title: 'ŁÓDŹ AS AN EXAMPLE OF SUCCESSFUL REVITALIZATION OF POST-INDUSTRIAL CITIES ', authors: 'Magdalena Rekść' },
  { id: '031', title: 'THE CONCEPT OF SMART RURAL DEVELOPMENT ON THE EXAMPLE OF THE MUNICIPALITY OF PETROVAC NA MLAVI', authors: 'Vedrana Babić Lazarević, Vladimir Pejanović and Aleksandra Prodanovic Stamenović' },
  { id: '032', title: 'IMPORTANCE OF INNOVATION MANAGEMENT SYSTEM IN ORGANIZATIONS ', authors: 'Branislava Bajić, Marina Janković, Vijoleta Vrhovac, Teodora Vučković, Srđan Vulanović and Dušanka Dakić' },
  { id: '033', title: 'TRENDS IN RURAL TOURISM: THE ENGINE FOR LOCAL DEVELOPMENT', authors: 'Ana Jovičić Vuković and Lazar Pavić' },
  { id: '034', title: 'DETERMINING CRITERIA WEIGHTS IN FRUITPRODUCTION USING FUZZY MCDM METHOD ', authors: 'Mirjana Radovic, Grujica Vico, Željko Stević, Danijel Mijić and Radomir Bodiroga' },
  { id: '035', title: 'TECHNOLOGICAL INNOVATIONS IN TOURISM BASED ON CIRCULAR ECONOMY', authors: 'Dragana Vuković, Božo Ilić, Ana Dukić and Marica Milošević' },
  { id: '036', title: 'WAYS TO AVOID BANKRUPTCIES: AVIATION INDUSTRY IN THE UNITED STATES ', authors: 'Rahaman Sheriff and Masatoshi Hara' },
  { id: '037', title: 'EXPLORING THE UTILITY OF BUSINESS INTELLIGENCE AND ARTIFICIAL INTELLIGENCE IMPLEMENTATION', authors: 'Tamara Gajić, Andrea Ivanišević, Snežana Knežević and Minja Bolesnikov' },
  { id: '038', title: 'ESSENTIAL PROJECT MANAGEMENT SKILLS FOR SUCCESSFUL ENTREPRENEURIAL LEADERSHIP ', authors: 'Aleksandra Simić, Angela Fajsi, Slobodan Morača, Jelena Borocki and Aleksandar Vekić' },
  { id: '039', title: 'THE IMPACT OF ARTIFICIAL INTELLIGENCE TECHNOLOGIES ON ORGANIZATIONAL STRUCTURE AND BUSINESS PROCESSES', authors: 'Branislav Stevanov, Predrag Vidicki, Tamara Bojanić and Petar Vrgović' },
  { id: '040', title: 'SUSTAINABLE INNOVATION AND TECHNOLOGY MANAGEMENT IN SERVICE COMPANIES. STATUS QUO. POTENTIALS. CHALLENGES. AN EXPLORATORY STUDY BASED ON AN ONLINE SURVEY OF HAIRDRESSING BUSINESSES IN GERMANY ', authors: 'Daniela Ludin, Robin Pflieger, Erika Mueller and Wanja Wellbrock' },
  { id: '041', title: 'ANALYSIS OF FACTORS AFFECTING EMPLOYEE SATISFACTION AND STRATEGIES FOR ITS IMPROVEMENT IN TOP MANAGEMENT OF A TRADING COMPANY', authors: 'Snežana Mirković, Mila Kavalić, Verica Gluvakov and Milan Nikolić' },
  { id: '042', title: 'HOW TO ELEVATE THE PRIVATE JET CHARTER EXPERIENCE? ', authors: 'Chaima Rhazaoui and David Annan' },
  { id: '043', title: 'THE INFLUENCE OF INDUSTRY 4.0 ON HUMAN RESOURCES MANAGEMENT', authors: 'Mirjana Jokanović-Đajić and Bojana Jokanović' },
  { id: '044', title: 'EXAMINING THE IMPACT OF DISRUPTIVE ATTRIBUTES OF THE INTERNET ECONOMY ON THE SUCCESS OF SMALL AND MEDIUM-SIZED ENTERPRISES IN THE REPUBLIC OF SERBIA ', authors: 'Dusko Petrovic and Goran Krstajic' },
  { id: '045', title: 'SELECTION OF CRITERIA FOR EVALUATING INNOVATIVE PROJECTS', authors: 'Ranka Sudžum, Slaviša Moljević, Angela Fajsi and Slobodan Morača' },
  { id: '046', title: 'BENEFITS OF WORK-LIFE BALANCE POLICIES FOR EMPLOYEES AND ORGANIZATIONS ', authors: 'Snežana Knežević, Tamara Gajić and Dragan Vukolić' },
  { id: '047', title: 'DETERMINATION OF THE MAIN RISK FACTORS INFLUENCING THE PROJECT SUCCESS: A SYSTEMATIC LITERATURE REVIEW', authors: 'Nina Banduka and Uglješa Marjanović' },
  { id: '048', title: 'THE HUMAN DIMENSION OF PROJECT SUCCESS: EXPLORING THE ROLE OF HIGH-PERFORMANCE WORK PRACTICES, TRUST, AND TEAM VOICE ', authors: 'Milena Savković, Danijela Ćirić Lalić, Danijela Gračanin and Tanja Todorović' },
  { id: '049', title: 'USING INTERPRETATIVE STRUCTURAL MODELING FOR ANALYZING KEY PROJECT MANAGERS\' AND PROJECT TEAM MEMBERS’ SKILLS, CRITICAL FOR PROJECT SUCCESS ', authors: 'Mirjana Jokanović Đajić, Budimirka Marinović and Danijela Ćirić Lalić' },
  { id: '050', title: 'STRATEGY TO DEVELOP PROJECT BY USING HYBRID APPROACH ', authors: 'Sunaina Paul, Minja Bolesnikov, Katarina Stojanović, Dario Silić and Milica Njegovan' },
  { id: '051', title: 'USE OF EXPLORATORY DATA ANALYSIS AND VISUALIZATION TECHNIQUES TO MEET ORGANIZATION STRATEGIC GOALS', authors: 'Sunaina Paul, Rudra Singh, Minja Bolesnikov and Ana Jovičić Vuković' },
  { id: '052', title: 'THE POTENTIAL OF MEDICINE IN THE REPUBLIC OF CROATIA ', authors: 'Maja Vizjak' },
  { id: '053', title: 'E-COMMERCE IN SLOVAKIA', authors: 'Branislav Dudic, Alexandra Mittelman and Jaroslav Vojtechovský' },
  { id: '054', title: 'PRINCIPLES AND MODELS OF STOCK MANAGEMENT BEFORE AND AFTER THE PANDEMIC ', authors: 'Goran Vujasinović, Vijoleta Vrhovac, Marina Janković, Željko Dudić and Dalibor Jeličić' },
  { id: '055', title: 'SUPPLY CHAIN FLEXIBILITY AND SMEs: THE ROLE OF HUMAN RESOURCE FLEXIBILITY', authors: 'Miroslav Dragić, Stevo Borojević and Nebojša Suvajčević' },
  { id: '056', title: 'FINANCIAL DEVELOPMENT AND ECONOMIC GROWTH IN SERBIA ', authors: 'Aleksandra Pavlović, Tanja Todorović, Dario Silić and Radivoj Prodanović' },
  { id: '057', title: 'ESG AND THE COST OF CAPITAL: EXAMPLES FROM EASTERN EUROPE', authors: 'Miroslav Ferenčak, Dušan Dobromirov and Mladen Radišić' },
  { id: '058', title: 'ARTIFICIAL INTELLIGENCE AND FINANCIAL MODELING ', authors: 'Ranko Bojanić, Marko Jović and Ivana Popović' },
  { id: '059', title: 'ANALYSIS OF THE INNOVATION SYSTEM IN SERBIA FROM A PUBLIC POLICY PERSPECTIVE', authors: 'Jovana Simić and Dragan Miletić' },
  { id: '060', title: 'WEALTHTECH: FUTURE TRENDS AND APPROACHES IN GLOBAL WEALTH MANAGEMENT ', authors: 'Bojana Jokanovic, Andrea Okanovic, Sandra Brkanlic, Slavko Ivkovic and Ivana Tomic' },
  { id: '061', title: 'THE INFLUENCE OF DEMOGRAPHIC DYNAMICS ON THE LABOR MARKET', authors: 'Branislav Sančanin, Katarina Stojanović and Aleksandra Penjišević' },
  { id: '062', title: 'VULNERABILITY IN AGRICULTURE - DATA ANALYSIS ', authors: 'Milena Zeljković, Tanja Vranić, Ljiljana Popović and Srdjan Popov' },
  { id: '063', title: 'THE IMPACT OF SUSTAINABILITY PRACTICES ON FINANCIAL PERFORMANCE: A REVIEW OF EMPIRICAL STUDIES', authors: 'Tanja Todorović, Aleksandra Pavlović, Ranko Makivić and Milena Savković' },
  { id: '064', title: 'OPTIMIZING FINANCIAL STRATEGIES IN INDIAN AQUACULTURE: A CASE STUDY OF WEST GODAVARI ', authors: 'Avinash Betala and Masatoshi Hara' },
  { id: '065', title: 'FOSTERING STARTUP ECOSYSTEMS THROUGH JAPANESE ENTREPRENEURSHIP IN LOWER-MIDDLE-INCOME ASEAN ECONOMIES', authors: 'Masatoshi Hara' },
  { id: '066', title: 'SUSTAINABLE BUSINESS MANAGEMENT IN DIGITAL SOUTHEAST ASIA: JAPANESE FIRMS IN LAO PDR ', authors: 'William Baber and Masatoshi Hara' },
  { id: '067', title: 'LEADERSHIP AS A FACTOR IN DESIGNING A FLEXIBLE COMPANY\'S ORGANIZATIONAL MODEL IN DYNAMIC BUSINESS CONDITIONS', authors: 'Nikola J. Gradojević, Vladimir Đ. Đaković and Snežana N. Marković' },
  { id: '068', title: 'LABOUR MARKET DYNAMICS – YOUTH MIGRATION FROM SERBIA ', authors: 'Ljubica Duđak and Agneš Slavić' },
  { id: '069', title: 'CLUSTER APPROACH TO TOURISM DEVELOPMENT IN THE FAR EAST AND ARCTIC AND FORMS OFSTATE SUPPORT FOR PRIVATE INVESTORS', authors: 'Dmitry Yakovenko' },
  { id: '070', title: 'WORKPLACE 3.0: DECODING SERBIAN MILLENNIAL GENERATION’S WORK BEHAVIOR ', authors: 'Ivana Jolović and Nevena Jolović' },
  { id: '071', title: 'SUSTAINABLE DEVELOPMENT EFFICIENCY OF EUROPEAN COUNTRIES', authors: 'Tijana Čobović, Gordana Savić and Milica Jovanović' },
  { id: '072', title: 'ECONOMICS OF HEALTHCARE IN NEUROSURGERY: COST EFFICIENCY AND FUNDING ANALYSIS IN THE MODERN HEALTH SYSTEM ', authors: 'Jagoš Golubović and Andrea Ivanišević' },
  { id: '073', title: 'SOCIO-ECONOMIC ANALYSIS AND EVALUATION OF THE CHOSEN VARIANT FOR LAND RECLAMATION DESIGN', authors: 'Andrea Ivanišević, Marijana Dukić Mijatović, Danijela Gračanin and Danijela Ćirić Lalić' },
  { id: '074', title: 'INTEGRATION OF RISK ASSESSMENT INTO FINANCIAL MODELS IN ORDER TO MAKE MORE SUCCESSFUL DECISIONS ', authors: 'Ksenija Krmpot and Ranko Bojanić' },
  { id: '075', title: 'INFLUENCE OF LASER WELDING SPEED ON WELD WIDTH, PENETRATION, REINFORCEMENT AND HEAT AFFECTED ZONE', authors: 'Nikolina Stojišić, Zoran Borović, Nikola Jevtić, Milan Pećanac and Sebastian Baloš' },
  { id: '076', title: 'CYBERSECURITY IN INDUSTRIAL INTERNET OF THINGS AND COLLABORATIVE ROBOTS: INDUSTRY 5.0 PERSPECTIVE ', authors: 'Dragana Slavić, Aleksa Komosar, Darko Stefanovic and Slavko Rakic' },
  { id: '077', title: 'THE FUTURE OF AGRICULTURAL SPRAYING: AI AND UAVS FOR SMART AND SUSTAINABLE PRACTICES', authors: 'Nebojša Novaković and Aleksandar Rikalović' },
  { id: '078', title: 'MAPPING THE INTERSECTION OF CYBERSECURITY AND INDUSTRY 5.0: A BIBLIOMETRIC ANALYSIS ', authors: 'Aleksa Komosar, Dragana Slavic, Slavko Rakic and Darko Stefanovic' },
  { id: '079', title: 'ONE SOLUTION OF LOW-COST LORA BASED IOT MODULAR CONTROL DEVICE', authors: 'Srdjan Tegeltija, Ivana Šenk, Laslo Tarjan, Gordana Ostojić and Stevan Stankovski' },
  { id: '080', title: 'DATA ANALYTICS CASE STUDY IN OPTIMIZING WELL WORKOVER PROCESS ', authors: 'Jelena Popara, Danijela Ćirić Lalić, Milena Savkovic and Bojan Lalić' },
  { id: '081', title: 'SMART GRID AND CHALLENGES OF GRID SUPPORT BY E-MOBILITY', authors: 'Velimir Strugar' },
  { id: '082', title: 'DIGITAL TRANSFORMATION STRATEGY DYNAMIC FOR UTILITY SMART GRIDS SYSTEM DYNAMICS MODELLING IN UNTANGLING COMPLEXITY ', authors: 'Minja Bolesnikov and Himadri Banerji' },
  { id: '083', title: 'CURRENT LANDSCAPE AND CHALLENGES: PRODUCT DEVELOPMENT OF ELECTRIC SCOOTERS IN INDIA', authors: 'Mahesh Patil and Minja Bolesnikov' },
  { id: '084', title: 'IMPACT OF GLOBALIZATION ON THE PERFORMANCE OF MEDIA SYSTEMS AND MEDIA ', authors: 'Goran Eror, Iva Šiđanin and Nemanja Tasić' },
  { id: '085', title: 'BRIDGING KNOWLEDGE, PROTECTION AND DEVELOPMENT GAPS THROUGH AN INTERDISCIPLINARY MULTISTAKEHOLDER APPROACH TO NATURAL HAZARDS RISK MANAGEMENT', authors: 'Nadia Netti and Martina de Cristofaro' },
  { id: '086', title: 'DIGITALIZATION POSITIVELY ASSOCIATES WITH THE ADOPTION OF SUSTAINABILITY PERFORMANCE METRICS IN MAINTENANCE PRACTICE: PRELIMINARY STUDY FINDINGS ', authors: 'Marko Orošnjak, Kristina Ristić and Nebojša Brkljač' },
  { id: '087', title: 'SUSTAINABILITY AS THE GOAL IN INNOVATIVE APPLICATIONS', authors: 'Mustafa Cem Aldag and Bulent Eker' },
  { id: '088', title: 'HOW TO INCREASE THE FUNCTIONS OF ARTIFICIAL INTELLIGENCE IN BUSINESSES ', authors: 'Bulent Eker and Mustafa Cem Aldag' },
  { id: '089', title: 'A METHOD FOR CHOOSING THE LOCATION OF PRODUCTION SYSTEMS USING A MULTIDISCIPLINARY APPROACH', authors: 'Daria Vidović, Nemanja Sremčev and Bojan Jerinić' },
  { id: '090', title: 'IMPLEMENTATION OF KAIZEN MANAGEMENT IN E-COMMERCE ', authors: 'Milica Živković, Nemanja Sremčev and Bojan Jerinić' },
  { id: '091', title: 'FLEXIBLE BATTERY CELL TESTING OF GEOMETRICAL PARAMETERS TO IMPROVE THE SUSTAINABILITY OF BATTERIES OVER THE ENTIRE LIFE CYCLE ', authors: 'Gernot Schlögl, Martin Scharf and Franz Haas' },
// Total papers: 131

  { id: '092', title: 'AI-DRIVEN DECISION-MAKING: A REVIEW ABOUT TRANSFORMING PROJECT MANAGEMENT THROUGH ADVANCED TECHNOLOGIES ', authors: 'Michael Wollweber' },
  { id: '093', title: 'COMPETITIVE NET-ZERO: A SIMULTANEOUS ENGINEERING APPROACH TO SUSTAINABLE PRODUCT DEVELOPMENT AND MANUFACTURING ', authors: 'Martin Scharf, Gernot Schlögl and Franz Haas' },
  { id: '094', title: 'PERMANENT INVOLVEMENT OF DIGITIZATION AND MODERN TECHNOLOGY IN THE DIRECTION OF SUSTAINABLE GROWTH IN THE TOURISM AND HOTEL INDUSTRY OF SERBIA ', authors: 'Tamara Gajić and Filip Đoković' },
  { id: '095', title: 'APPLICATION OF THE TAGUCHI METHOD FOR OPTIMIZING THE 3D PRINTING PROCESS FROM THE ASPECTS OF PRODUCTIVITY AND DIMENSIONAL ACCURACY ', authors: 'Dejan Bozic, Mijodrag Milosevic, Zeljko Santosi, Stevo Borojevic, Borislav Savkovic and Dejan Lukic' },
  { id: '096', title: 'THE ROLE OF TRANSFORMATIVE TECHNOLOGIES IN ENHANCING THE QUALITY OF NURSING CARE DURING THE COVID-19 PANDEMIC ', authors: 'Nahid Kia-Rostami' },
  { id: '097', title: 'INFLUENCE OF STIMULUS FORMAT ON VIRTUAL CHARACTER PERCEPTION ', authors: 'Gala Golubović, Sandra Dedijer, Jelena Kerac and Teodora Gvoka' },
  { id: '098', title: 'THE ROLE OF VALUE CO-CREATION IN THE BRANDING OF FUNCTIONAL URBAN AREAS: A DELPHI ANALYSIS ', authors: 'Anna Matwiejczyk' },
  { id: '099', title: 'EFFECTS OF CONSUMER ETHNOCENTRISM, COSMOPOLITANISM, XENOCENTRISM, METACOGNITIVE, AND COGNITIVE CULTURAL INTELLIGENCE ON PURCHASING FAMOUS WORLD BRANDS ', authors: 'Stefan Zdravković, Dragana Gašević, Dragana Tomašević and Marija Vranješ' },
  { id: '100', title: 'THE FUTURE OF THE NEWSPAPER INDUSTRY ', authors: 'Gregor Franken' },
  { id: '101', title: 'THE FUTURE OF GENERATIVE AI IN DIGITAL MARKETING: CHALLENGES AND OPPORTUNITIES ', authors: 'Marija Đaković and Aleksandar Rikalovic' },
  { id: '102', title: 'RESHAPING THE FUTURE OF PREPRESS WITH ARTIFICIAL INTELLIGENCE ', authors: 'Sandra Dedijer, Nemanja Kašiković, Živko Pavlović, Željko Zeljković, Boris Dumnić, Aleksandar Anđelković and Velibor Premčevski' },
  { id: '103', title: 'ANALYSIS OF THE USE OF SOCIAL MEDIA MARKETING WITH AN OVERVIEW ON GRAPHIC DESIGN ON THE EXAMPLE OF TREBINJE WINERIES ', authors: 'Mirjana Miljanović, Igor Dutina and Marina Milićević' },
  { id: '104', title: 'THE USE OF ARTIFICIAL INTELLIGENCE IN CREATIVE ADVERTISING CAMPAIGNS ', authors: 'Dunja Bošković, Jelena Spajić, Bojana Milić, Ksenija Mitrović and Danijela Lalić' },
  { id: '105', title: 'MARKETING IN IT INDUSTRY: AN ANALYSIS OF GRADUATES\' COMPETENCIES AND CAREER PATHS ', authors: 'Jelena Spajić, Nikolina Milošević, Dunja Bošković, Bojana Milić and Danijela Lalić' },
  { id: '106', title: 'RELATIONSHIP OF QUALITY, PRICE AND TOILET SOAP CONSUMPTION ', authors: 'Aleksandra Borković, Tatjana Botić, Pero Dugić, Dijana Drljača, Tijana Đuričić, Dajana Dragić, Sanda Pilipović and Branka Miladinović' },
  { id: '107', title: 'THE IMPORTANCE OF URBAN GRAPHIC DESIGN IN PLANNING URBAN GREEN SPACE ', authors: 'Slađana Milovanović and Katarina Stojanović' },
  { id: '108', title: 'ENHANCING CUSTOMER JOURNEY THROUGH PROCESS MINING: A LITERATURE REVIEW AND FUTURE RESEARCH DIRECTIONS ', authors: 'Igor Mandic' },
  { id: '109', title: 'CYBER RISKS OF CYBERLOAFING - HRM PERSPECTIVES OF ORGANIZATIONAL SECURITY ', authors: 'Maja Križanec Cvitković, Ana Globočnik Žunac and Marko Antić' },
  { id: '110', title: 'THE FINANCIAL AND ECONOMIC RISKS IN THE RISK ASSESSMENT MODEL MADE FOR WASTEWATER TREATMENT PLANT ', authors: 'Jovana Topalić, Vladimir Mučenski and Andrea Ivanišević' },
  { id: '111', title: 'USING MACHINE LEARNING PRACTICES TO DETECT FRAUD AND RISK MANAGEMENT ', authors: 'Enio Yzeiri, Egla Mansi, Nerajda Feruni and Aida Bitri' },
  { id: '112', title: 'STRATEGIES FOR INDUSTRY: ENGINEERING SOLUTIONS IN NOISE CONTROL AND RISK MANAGEMENT ', authors: 'Selena Samardžić and Robert Lakatoš' },
  { id: '113', title: 'EFFECT OF HEMP FIBER PRE-TREATMENT ON REPAIR CEMENT MORTAR MECHANICAL PROPERTIES ', authors: 'Tiana Milović, Slobodan Šupić, Vesna Bulatović and Vladan Pantić' },
  { id: '114', title: 'INNOVATIVE APPROACHES TO NATURAL DISASTER MANAGEMENT: THE ROLE OF AI AND IoT ', authors: 'Ognjen Dopuđ and Aleksandra Sitarević' },
  { id: '115', title: 'EFFECTIVE NOISE MANAGEMENT – THE ROLE OF REGULAR CRANE MAINTENANCE ', authors: 'Željana Kužet, Vladimir Mučenski and Selena Samardžić' },
  { id: '116', title: 'EXPLORING THE POTENTIAL OF SEDIMENT BENEFICIAL USE: ECONOMIC VIABILITY AND ENVIRONMENTAL SUSTAINABILITY ', authors: 'Dragana Tomašević Pilipović, Andrea Ivanišević, Đurđa Kekrez, Miloš Šešlija and Igor Peško' },
  { id: '117', title: 'POSSIBILITIES FOR FOSTERING URBAN DEVELOPMENT IN CITIES AND REGIONS THROUGH THE IMPLEMENTATION OF INTERDISCIPLINARY RESEARCH OUTCOMES WITHIN THE FRAMEWORK OF INTERNATIONAL PROJECTS ', authors: 'Milena Krklješ and Dejana Nedučin' },
  { id: '118', title: 'IMPACT OF INDOOR AIR QUALITY ON WORKERS HEALTH AND PRODUCTIVITY ', authors: 'Dragan Adamović' },
  { id: '119', title: 'CYBER SECURITY RISKS WHILE DRIVING CAR ', authors: 'Miloš Stanojević, Mladen Babić, Srđan Tegeltija and Gordana Ostojić' },
  { id: '120', title: 'CYBERSECURITY ISSUES OF COMPUTING SYSTEMS ', authors: 'Stevan Stankovski and Gordana Ostojić' },
  { id: '121', title: 'AUTOMATIC IDENTIFICATION SYSTEMS IN INDUSTRY APPLICATIONS ', authors: 'Gordana Ostojić and Stevan Stankovski' },
  { id: '122', title: 'ARTIFICIAL INTELLIGENCE AND DEEP LEARNING ALGORITHMS: A POST-SMART PATH FOR CITIES ', authors: 'Katarina Stojanović, Božo Ilić, Đorđe Mihailović, Ksenija Orlandić Osmajić and Radovan Pejanović' },
  { id: '123', title: 'INTEGRATING ENVIRONMENTAL AND SOCIAL MANAGEMENT PLANS IN SUSTAINABLE HYDROMELIORATION PRACTICES: A CASE STUDY OF THE VOJVODINA REGION ', authors: 'Nevena Živančev, Maja Petrović, Zorica Mirosavljević and Nemanja Stanisavljević' },
  { id: '124', title: 'RIVER SEDIMENTS AS ROAD MATERIAL ', authors: 'Miloš Šešlija, Anka Starčev-Ćurčin and Dragana Tomašević-Pilipović' },
  { id: '125', title: 'CONCEPTUAL DESIGN FOR URBAN STREET RECONSTRUCTION USING THE SHARED SPACE APPROACH ', authors: 'Ivan Cvitković, Katarina Stojanović and Ante Klečina' },
  { id: '126', title: 'ENGINEERS ENTREPRENEURS: ENHANCING SKILLS OF STEM STUDENTS ', authors: 'Mila Velkovska, Bojan Jovanovski, Radmil Polenakovikj, Trajce Velkovski and Yao Amevi Amessinou Sossou' },
  { id: '127', title: 'VISION OF IDVOR AS A SMART VILLAGE OF THE 21ST CENTURY ', authors: 'Katarina Stojanović, Ivan Bošnjak, Mina Zirojević and Rejhan Kurtović' },
  { id: '128', title: 'COALESCENCE FILTRATION IN SUSTAINABLE ENVIRONMENTAL PRACTICE ', authors: 'Dunja Sokolović' },
  { id: '129', title: 'ADVANCEMENTS IN THE GLOBAL GREEN HYDROGEN ECONOMY ', authors: 'Barunava Banerjee and Minja Bolesnikov' },
  { id: '130', title: 'FIRE RESISTANCE OF MASONRY MORTAR BLENDED WITH ENVIRONMENTALLY-FRIENDLY MATERIALS ', authors: 'Vladan Pantić, Slobodan Šupić, Suzana Draganić and Igor Džolev' },
  { id: '131', title: 'ACCESS TO JUSTICE IN THE FIELD OF THE ENVIRONMENT WITH SPECIAL REFERENCE TO LIABILITY FOR ENVIRONMENTAL DAMAGE, ENVIRONMENTAL CRIMINALITY AND ENVIRONMENTAL FORENSICS IN REPUBLIC OF SERBIA ', authors: 'Tina Janjatović' },
  { id: '132', title: 'THE ECOCRATIC TURN KEEPING OR LOSING THE CONTROL OF M-E-O', authors: 'Lazar Imre' },
];

// Filename mapping
const filenameMap: Record<string, string> = {
  '001': '001-Rosietall.pdf', '002': '002Vujovicetall.pdf', '003': '003_Fabris_et_all.pdf',
  '004': '004-Eric_et_all.pdf', '005': '005-Stankovic_et_all.pdf', '006': '006-Anisic_et_all.pdf',
  '007': '007-Djuricic_et_all.pdf', '008': '008-Sitarevic_et_all-1.pdf', '009': '009-Mitrovic_et_all.pdf',
  '010': '010-Vorina_et_all.pdf', '011': '011-Stevanovic_et_all.pdf', '012': '012-Grebic_et_all.pdf',
  '013': '013-Milosevic_et_all.pdf', '014': '014-Milosevic_et_all.pdf', '015': '015-Ratic_et_all.pdf',
  '016': '016-Slavic_et_all.pdf', '017': '017-Lecic.pdf', '018': '018-Pavlovic_et_all.pdf',
  '019': '019-Smaiya_et_all.pdf', '020': '020-Joseph_et_all.pdf', '021': '021-Fominykh_et_all.pdf',
  '022': '022-Thompson_Okoye.pdf', '023': '023-Sikoparija_et_all.pdf', '024': '024-Gardasevic_et_all.pdf',
  '025': '025-Milicevic_et_all.pdf', '026': '026-Jokic_et_all.pdf', '027': '027-Dukic_Mijatovic_et_all.pdf',
  '028': '028-Milosevic_et_all.pdf', '029': '029-Takaci_et_all.pdf', '030': '030-Reksc.pdf',
  '031': '031-Lazarevic_et_all.pdf', '032': '032-Bajic_et_all.pdf', '033': '033-Vukovic_et_all.pdf',
  '034': '034-Radovic_et_all.pdf', '035': '035-Vukovic_et_all.pdf', '036': '036-Sheriff_et_all.pdf',
  '037': '037-Gajic_et_all.pdf', '038': '038-Simic_et_all.pdf', '039': '039-Stevanov_et_all.pdf',
  '040': '040-Ludin_et_all.pdf', '041': '041-Mirkovic_et_all.pdf', '042': '042-Rhazaoui_et_all.pdf',
  '043': '043-Jokanovic-Djajic_et_all.pdf', '044': '044-Petrovic_et_all.pdf', '045': '045-Sudzum_et_all.pdf',
  '046': '046-Knezevic_et_all.pdf', '047': '047-Banduka_et_all.pdf', '048': '048-Savkovic_et_all.pdf',
  '049': '049-Jokanovic-Djajic_et_all.pdf', '050': '050-Paul_et_all.pdf', '051': '051-Paul_et_all.pdf',
  '052': '052-Vizjak.pdf', '053': '053-Dudic_et_all.pdf', '054': '054-Vujasinovic_et_all.pdf',
  '055': '055-Dragic_et_all.pdf', '056': '056-Pavlovic_et_all.pdf', '057': '057-Ferencak_et_all.pdf',
  '058': '058-Bojanic_et_all.pdf', '059': '059-Simic_et_all.pdf', '060': '060-Jokanovic_et_all.pdf',
  '061': '061-Sancanin_et_all.pdf', '062': '062-Zeljkovic_et_all.pdf', '063': '063-Todorovic_et_all.pdf',
  '064': '064-Betala_et_all.pdf', '065': '065-Hara_et_all.pdf', '066': '066-Baber_et_all.pdf',
  '067': '067-Gradojevic_et_all.pdf', '068': '068-Dudjak_et_all.pdf', '069': '069-Yakovenko.pdf',
  '070': '070-Jolovic_et_all.pdf', '071': '071-Cobanovic_et_all.pdf', '072': '072-Golubovic_et_all.pdf',
  '073': '073-Ivanisevic_et_all.pdf', '074': '074-Krmpot_et_all.pdf', '075': '075-Stojisic_et_all.pdf',
  '076': '076-Slavic_et_all.pdf', '077': '077-Novakovic_et_all.pdf', '078': '078-Komosar_et_all.pdf',
  '079': '079-Tegeltija_et_all.pdf', '080': '080-Popara_et_all.pdf', '081': '081-Strugar.pdf',
  '082': '082-Bolesnikov_et_all.pdf', '083': '083-Patil_et_all.pdf', '084': '084-Eror_et_all.pdf',
  '085': '085-Netti_et_all.pdf', '086': '086-Orosnjak_et_all.pdf', '087': '087-Cem_Aldag_et_all.pdf',
  '088': '088-Eker_et_all.pdf', '089': '089-Vidovic_et_all.pdf', '090': '090-Zivkovic_et_all.pdf',
  '091': '091-Sclogl_et_all.pdf', '092': '092-Wollweber.pdf', '093': '093-Scharf_et_all.pdf',
  '094': '094-Gajic_et_all.pdf', '095': '095-Bozic_et_all.pdf', '096': '096-Kia-Rostami.pdf',
  '097': '097-Golubovic_et_all.pdf', '098': '098-Matwiejczyk.pdf', '099': '099-Zdravkovic_et_all.pdf',
  '100': '100-Franken.pdf', '101': '101-Djakovic_et_all.pdf', '102': '102-Dedijer_et_all.pdf',
  '103': '103-Miljanovic_et_all.pdf', '104': '104-Boskovic_et_all.pdf', '105': '105-Spajic_et_all.pdf',
  '106': '106-Borkovic_et_all.pdf', '107': '107-Milovanovic_et_all.pdf', '108': '108-Mandic.pdf',
  '109': '109-Krizanec_Cvitkovic_et_all.pdf', '110': '110-Topalic_et_all.pdf', '111': '111-Yzeiri_et_all.pdf',
  '112': '112-Samardzic_et_all.pdf', '113': '113-Milovic_et_all.pdf', '114': '114-Dopudj_et_all.pdf',
  '115': '115-Kuzet_et_all.pdf', '116': '116-Tomasevic_Pilipovic_et_all.pdf', '117': '117-Krkljes_et_all.pdf',
  '118': '118-Adamovic.pdf', '119': '119_Stanojevic_et_all.pdf', '120': '120-Stankovski_et_all.pdf',
  '121': '121-Ostojic_et_all.pdf', '122': '122-Stojanovic_et_all.pdf', '123': '123-Zivancev_et_all.pdf',
  '124': '124-Seslija_et_all.pdf', '125': '125-Cvitkovic_et_all.pdf', '126': '126-Velkovska_et_all.pdf',
  '127': '127-Stojanovic_et_all.pdf', '128': '128-Sokolovic.pdf', '129': '129-Banerjee_et_all.pdf',
  '130': '130-Pantic_et_all.pdf', '131': '131-Janjatovic.pdf', '132': '132-Lazar-1.pdf'
};

export const getFilename = (id: string) => filenameMap[id] || `${id}.pdf`;
